vars:
  BUNDLE_ID:
    default: ar.com.tero
  PACKAGE_NAME:
    default: ar.com.tero
  VERSION_NAME:
  VERSION_CODE:
    default: 52
  MIN_SDK:
    default: '= 29'
  SDK:
    default: '= 35'
  FIX_ANDROIDX_COMPAT_VERSION:
    default: "= '1.6.1'"

platforms:
  android:
    packageName: $PACKAGE_NAME
    versionName: $VERSION_NAME
    versionCode: $VERSION_CODE
    manifest:
      - file: AndroidManifest.xml
        target: manifest/application/activity
        attrs:
          android:screenOrientation: portrait

      - file: AndroidManifest.xml
        target: manifest/application/activity
        inject: |
          <intent-filter android:autoVerify="true">
              <action android:name="android.intent.action.VIEW" />
              <category android:name="android.intent.category.DEFAULT" />
              <category android:name="android.intent.category.BROWSABLE" />
              <data android:scheme="https" android:host="tero.com.ar" />
          </intent-filter>

      - file: AndroidManifest.xml
        target: manifest
        attrs:
          xmlns:tools: http://schemas.android.com/tools

      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="com.google.android.gms.permission.AD_ID" tools:node="remove"/>

    gradle:
      - file: variables.gradle
        target:
          ext:
            minSdkVersion:
        replace:
          - minSdkVersion: $MIN_SDK

      - file: variables.gradle
        target:
          ext:
        insertType: 'variable'
        insert:
          - rgcfaIncludeGoogle: 'true'

      - file: variables.gradle
        target:
          ext:
            androidxAppCompatVersion:
        replace:
          - androidxAppCompatVersion: $FIX_ANDROIDX_COMPAT_VERSION

    res:
      - path: mipmap-anydpi-v26
        file: ic_launcher.xml
        source: resources/ic_launcher.xml
      - path: mipmap-anydpi-v26
        file: ic_launcher_round.xml
        source: resources/ic_launcher.xml

    copy:
      - src: ../google-services.json
        dest: app/google-services.json
