export enum MENU_OPTION_ID {
  DASHBOARD = 'DASHBOARD',
  NEIGHBORS = 'NEIGHBORS',
  NEIGHBORHOOD = 'NEIGHBORHOOD',
  CONTACTS = 'CONTACTS',
  CONFIG = 'CONFIG'
}

export enum TOPIC_SUBSCRIPTION {
  GARBAGE = 'garbage',
  NEW_TOPIC = 'newTopic',
  USER_SECURITY_INVOICE = 'userSecurityInvoice',
  GROUP_SECURITY_INVOICE = 'groupSecurityInvoice',
  NEW_ECOMMERCE_PRODUCT = 'newEcommerceProduct'
}

export const LOGO_PATH = '/assets/favicons/favicon.ico';
export const NO_ID = -1;
export const NAME_MIN_LENGTH = 2;
export const NAME_MAX_LENGTH = 128;
export const EMAIL_MIN_LENGTH = 6;
export const EMAIL_MAX_LENGTH = 128;
export const PHONE_MIN_LENGTH = 2;
export const PHONE_MAX_LENGTH = 128;
export const LONG_TEXT_MAX_LENGTH = 256;
export const SECURITY_GROUPS = [1, 2, 3, 4, 5, 6];
export const ALARMS = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12];
export const ALARM_CONTROLS = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30];
export const WHATSAPP_URL = 'https://api.whatsapp.com/send?phone=549';

export const DEFAULT_USER_PICTURE = 'picture_user.svg';

export const MONTHS = ['JANUARY', 'FEBRUARY', 'MARCH', 'APRIL', 'MAY', 'JUNE', 'JULY', 'AUGUST', 'SEPTEMBER', 'OCTOBER', 'NOVEMBER', 'DECEMBER'];

export const LOTS = [
  {
    number: 0,
    district: 0,
    cadastralNumber: 0,
    cadastralJurisdiction: 0,
    section: '',
    subdivision: 0,
    block: '',
    parcel: 0,
    neighbors: []
  },
  {
    number: 1,
    district: 114,
    cadastralNumber: 41259,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10Z',
    parcel: 1,
    neighbors: []
  },
  {
    number: 2,
    district: 114,
    cadastralNumber: 41260,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10Z',
    parcel: 2,
    neighbors: []
  },
  {
    number: 3,
    district: 114,
    cadastralNumber: 41261,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10Z',
    parcel: 3,
    neighbors: []
  },
  {
    number: 4,
    district: 114,
    cadastralNumber: 41262,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10Z',
    parcel: 4,
    neighbors: []
  },
  {
    number: 5,
    district: 114,
    cadastralNumber: 41263,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10Z',
    parcel: 5,
    neighbors: []
  },
  {
    number: 6,
    district: 114,
    cadastralNumber: 41264,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10Z',
    parcel: 6,
    neighbors: []
  },
  {
    number: 7,
    district: 114,
    cadastralNumber: 41265,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10Z',
    parcel: 7,
    neighbors: []
  },
  {
    number: 8,
    district: 114,
    cadastralNumber: 41266,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10Z',
    parcel: 8,
    neighbors: []
  },
  {
    number: 9,
    district: 114,
    cadastralNumber: 41226,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10W',
    parcel: 16,
    neighbors: []
  },
  {
    number: 10,
    district: 114,
    cadastralNumber: 41225,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10W',
    parcel: 15,
    neighbors: []
  },
  {
    number: 11,
    district: 114,
    cadastralNumber: 41224,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10W',
    parcel: 14,
    neighbors: []
  },
  {
    number: 12,
    district: 114,
    cadastralNumber: 41223,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10W',
    parcel: 13,
    neighbors: []
  },
  {
    number: 13,
    district: 114,
    cadastralNumber: 41222,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10W',
    parcel: 12,
    neighbors: []
  },
  {
    number: 14,
    district: 114,
    cadastralNumber: 41221,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10W',
    parcel: 11,
    neighbors: []
  },
  {
    number: 15,
    district: 114,
    cadastralNumber: 41220,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10W',
    parcel: 10,
    neighbors: []
  },
  {
    number: 16,
    district: 114,
    cadastralNumber: 41219,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10W',
    parcel: 9,
    neighbors: []
  },
  {
    number: 17,
    district: 114,
    cadastralNumber: 41211,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10W',
    parcel: 1,
    neighbors: []
  },
  {
    number: 18,
    district: 114,
    cadastralNumber: 41212,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10W',
    parcel: 2,
    neighbors: []
  },
  {
    number: 19,
    district: 114,
    cadastralNumber: 41213,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10W',
    parcel: 3,
    neighbors: []
  },
  {
    number: 20,
    district: 114,
    cadastralNumber: 41214,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10W',
    parcel: 4,
    neighbors: []
  },
  {
    number: 21,
    district: 114,
    cadastralNumber: 41215,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10W',
    parcel: 5,
    neighbors: []
  },
  {
    number: 22,
    district: 114,
    cadastralNumber: 41216,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10W',
    parcel: 6,
    neighbors: []
  },
  {
    number: 23,
    district: 114,
    cadastralNumber: 41217,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10W',
    parcel: 7,
    neighbors: []
  },
  {
    number: 24,
    district: 114,
    cadastralNumber: 41218,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10W',
    parcel: 8,
    neighbors: []
  },
  {
    number: 25,
    district: 114,
    cadastralNumber: 41168,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10R',
    parcel: 16,
    neighbors: []
  },
  {
    number: 26,
    district: 114,
    cadastralNumber: 41167,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10R',
    parcel: 15,
    neighbors: []
  },
  {
    number: 27,
    district: 114,
    cadastralNumber: 41166,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10R',
    parcel: 14,
    neighbors: []
  },
  {
    number: 28,
    district: 114,
    cadastralNumber: 41165,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10R',
    parcel: 13,
    neighbors: []
  },
  {
    number: 29,
    district: 114,
    cadastralNumber: 41164,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10R',
    parcel: 12,
    neighbors: []
  },
  {
    number: 30,
    district: 114,
    cadastralNumber: 41163,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10R',
    parcel: 11,
    neighbors: []
  },
  {
    number: 31,
    district: 114,
    cadastralNumber: 41162,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10R',
    parcel: 10,
    neighbors: []
  },
  {
    number: 32,
    district: 114,
    cadastralNumber: 41161,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10R',
    parcel: 9,
    neighbors: []
  },
  {
    number: 33,
    district: 114,
    cadastralNumber: 29845,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10R',
    parcel: 1,
    neighbors: []
  },
  {
    number: 34,
    district: 114,
    cadastralNumber: 41154,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10R',
    parcel: 2,
    neighbors: []
  },
  {
    number: 35,
    district: 114,
    cadastralNumber: 41155,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10R',
    parcel: 3,
    neighbors: []
  },
  {
    number: 36,
    district: 114,
    cadastralNumber: 41156,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10R',
    parcel: 4,
    neighbors: []
  },
  {
    number: 37,
    district: 114,
    cadastralNumber: 41157,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10R',
    parcel: 5,
    neighbors: []
  },
  {
    number: 38,
    district: 114,
    cadastralNumber: 41158,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10R',
    parcel: 6,
    neighbors: []
  },
  {
    number: 39,
    district: 114,
    cadastralNumber: 41159,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10R',
    parcel: 7,
    neighbors: []
  },
  {
    number: 40,
    district: 114,
    cadastralNumber: 41160,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10R',
    parcel: 8,
    neighbors: []
  },
  {
    number: 41,
    district: 114,
    cadastralNumber: 41110,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10k',
    parcel: 16,
    neighbors: []
  },
  {
    number: 42,
    district: 114,
    cadastralNumber: 41109,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10k',
    parcel: 15,
    neighbors: []
  },
  {
    number: 43,
    district: 114,
    cadastralNumber: 41108,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10k',
    parcel: 14,
    neighbors: []
  },
  {
    number: 44,
    district: 114,
    cadastralNumber: 41107,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10k',
    parcel: 13,
    neighbors: []
  },
  {
    number: 45,
    district: 114,
    cadastralNumber: 41106,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10k',
    parcel: 12,
    neighbors: []
  },
  {
    number: 46,
    district: 114,
    cadastralNumber: 41105,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10k',
    parcel: 11,
    neighbors: []
  },
  {
    number: 47,
    district: 114,
    cadastralNumber: 41104,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10k',
    parcel: 10,
    neighbors: []
  },
  {
    number: 48,
    district: 114,
    cadastralNumber: 41103,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10k',
    parcel: 9,
    neighbors: []
  },
  {
    number: 49,
    district: 114,
    cadastralNumber: 29844,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10k',
    parcel: 1,
    neighbors: []
  },
  {
    number: 50,
    district: 114,
    cadastralNumber: 41096,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10k',
    parcel: 2,
    neighbors: []
  },
  {
    number: 51,
    district: 114,
    cadastralNumber: 41097,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10k',
    parcel: 3,
    neighbors: []
  },
  {
    number: 52,
    district: 114,
    cadastralNumber: 41098,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10k',
    parcel: 4,
    neighbors: []
  },
  {
    number: 53,
    district: 114,
    cadastralNumber: 41099,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10k',
    parcel: 5,
    neighbors: []
  },
  {
    number: 54,
    district: 114,
    cadastralNumber: 41100,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10k',
    parcel: 6,
    neighbors: []
  },
  {
    number: 55,
    district: 114,
    cadastralNumber: 41101,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10k',
    parcel: 7,
    neighbors: []
  },
  {
    number: 56,
    district: 114,
    cadastralNumber: 41102,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10k',
    parcel: 8,
    neighbors: []
  },
  {
    number: 57,
    district: 114,
    cadastralNumber: 41058,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10E',
    parcel: 16,
    neighbors: []
  },
  {
    number: 58,
    district: 114,
    cadastralNumber: 41057,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10E',
    parcel: 15,
    neighbors: []
  },
  {
    number: 59,
    district: 114,
    cadastralNumber: 41056,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10E',
    parcel: 14,
    neighbors: []
  },
  {
    number: 60,
    district: 114,
    cadastralNumber: 41055,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10E',
    parcel: 13,
    neighbors: []
  },
  {
    number: 61,
    district: 114,
    cadastralNumber: 41054,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10E',
    parcel: 12,
    neighbors: []
  },
  {
    number: 62,
    district: 114,
    cadastralNumber: 41053,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10E',
    parcel: 11,
    neighbors: []
  },
  {
    number: 63,
    district: 114,
    cadastralNumber: 41052,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10E',
    parcel: 10,
    neighbors: []
  },
  {
    number: 64,
    district: 114,
    cadastralNumber: 41051,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10E',
    parcel: 9,
    neighbors: []
  },
  {
    number: 65,
    district: 114,
    cadastralNumber: 41267,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10AA',
    parcel: 1,
    neighbors: []
  },
  {
    number: 66,
    district: 114,
    cadastralNumber: 41268,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10AA',
    parcel: 2,
    neighbors: []
  },
  {
    number: 67,
    district: 114,
    cadastralNumber: 41269,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10AA',
    parcel: 3,
    neighbors: []
  },
  {
    number: 68,
    district: 114,
    cadastralNumber: 41270,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10AA',
    parcel: 4,
    neighbors: []
  },
  {
    number: 69,
    district: 114,
    cadastralNumber: 41271,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10AA',
    parcel: 5,
    neighbors: []
  },
  {
    number: 70,
    district: 114,
    cadastralNumber: 41272,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10AA',
    parcel: 6,
    neighbors: []
  },
  {
    number: 71,
    district: 114,
    cadastralNumber: 41246,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10X',
    parcel: 20,
    neighbors: []
  },
  {
    number: 72,
    district: 114,
    cadastralNumber: 41245,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10X',
    parcel: 19,
    neighbors: []
  },
  {
    number: 73,
    district: 114,
    cadastralNumber: 41244,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10X',
    parcel: 18,
    neighbors: []
  },
  {
    number: 74,
    district: 114,
    cadastralNumber: 41243,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10X',
    parcel: 17,
    neighbors: []
  },
  {
    number: 75,
    district: 114,
    cadastralNumber: 41242,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10X',
    parcel: 16,
    neighbors: []
  },
  {
    number: 76,
    district: 114,
    cadastralNumber: 41241,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10X',
    parcel: 15,
    neighbors: []
  },
  {
    number: 77,
    district: 114,
    cadastralNumber: 41227,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10X',
    parcel: 1,
    neighbors: []
  },
  {
    number: 78,
    district: 114,
    cadastralNumber: 41228,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10X',
    parcel: 2,
    neighbors: []
  },
  {
    number: 79,
    district: 114,
    cadastralNumber: 41229,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10X',
    parcel: 3,
    neighbors: []
  },
  {
    number: 80,
    district: 114,
    cadastralNumber: 41230,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10X',
    parcel: 4,
    neighbors: []
  },
  {
    number: 81,
    district: 114,
    cadastralNumber: 41231,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10X',
    parcel: 5,
    neighbors: []
  },
  {
    number: 82,
    district: 114,
    cadastralNumber: 41232,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10X',
    parcel: 6,
    neighbors: []
  },
  {
    number: 83,
    district: 114,
    cadastralNumber: 41233,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10X',
    parcel: 7,
    neighbors: []
  },
  {
    number: 84,
    district: 114,
    cadastralNumber: 41234,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10X',
    parcel: 8,
    neighbors: []
  },
  {
    number: 85,
    district: 114,
    cadastralNumber: 41235,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10X',
    parcel: 9,
    neighbors: []
  },
  {
    number: 86,
    district: 114,
    cadastralNumber: 41236,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10X',
    parcel: 10,
    neighbors: []
  },
  {
    number: 87,
    district: 114,
    cadastralNumber: 41187,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10S',
    parcel: 20,
    neighbors: []
  },
  {
    number: 88,
    district: 114,
    cadastralNumber: 41186,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10S',
    parcel: 19,
    neighbors: []
  },
  {
    number: 89,
    district: 114,
    cadastralNumber: 41185,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10S',
    parcel: 18,
    neighbors: []
  },
  {
    number: 90,
    district: 114,
    cadastralNumber: 41184,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10S',
    parcel: 17,
    neighbors: []
  },
  {
    number: 91,
    district: 114,
    cadastralNumber: 41183,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10S',
    parcel: 16,
    neighbors: []
  },
  {
    number: 92,
    district: 114,
    cadastralNumber: 41182,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10S',
    parcel: 15,
    neighbors: []
  },
  {
    number: 93,
    district: 114,
    cadastralNumber: 41181,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10S',
    parcel: 14,
    neighbors: []
  },
  {
    number: 94,
    district: 114,
    cadastralNumber: 41180,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10S',
    parcel: 13,
    neighbors: []
  },
  {
    number: 95,
    district: 114,
    cadastralNumber: 41179,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10S',
    parcel: 12,
    neighbors: []
  },
  {
    number: 96,
    district: 114,
    cadastralNumber: 41178,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10S',
    parcel: 11,
    neighbors: []
  },
  {
    number: 97,
    district: 114,
    cadastralNumber: 29849,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10S',
    parcel: 1,
    neighbors: []
  },
  {
    number: 98,
    district: 114,
    cadastralNumber: 41169,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10S',
    parcel: 2,
    neighbors: []
  },
  {
    number: 99,
    district: 114,
    cadastralNumber: 41170,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10S',
    parcel: 3,
    neighbors: []
  },
  {
    number: 100,
    district: 114,
    cadastralNumber: 41171,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10S',
    parcel: 4,
    neighbors: []
  },
  {
    number: 101,
    district: 114,
    cadastralNumber: 41172,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10S',
    parcel: 5,
    neighbors: []
  },
  {
    number: 102,
    district: 114,
    cadastralNumber: 41173,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10S',
    parcel: 6,
    neighbors: []
  },
  {
    number: 103,
    district: 114,
    cadastralNumber: 41174,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10S',
    parcel: 7,
    neighbors: []
  },
  {
    number: 104,
    district: 114,
    cadastralNumber: 41175,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10S',
    parcel: 8,
    neighbors: []
  },
  {
    number: 105,
    district: 114,
    cadastralNumber: 41176,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10S',
    parcel: 9,
    neighbors: []
  },
  {
    number: 106,
    district: 114,
    cadastralNumber: 41177,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10S',
    parcel: 10,
    neighbors: []
  },
  {
    number: 107,
    district: 114,
    cadastralNumber: 41129,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10M',
    parcel: 20,
    neighbors: []
  },
  {
    number: 108,
    district: 114,
    cadastralNumber: 41128,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10M',
    parcel: 19,
    neighbors: []
  },
  {
    number: 109,
    district: 114,
    cadastralNumber: 41127,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10M',
    parcel: 18,
    neighbors: []
  },
  {
    number: 110,
    district: 114,
    cadastralNumber: 41126,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10M',
    parcel: 17,
    neighbors: []
  },
  {
    number: 111,
    district: 114,
    cadastralNumber: 41125,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10M',
    parcel: 16,
    neighbors: []
  },
  {
    number: 112,
    district: 114,
    cadastralNumber: 41124,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10M',
    parcel: 15,
    neighbors: []
  },
  {
    number: 113,
    district: 114,
    cadastralNumber: 41123,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10M',
    parcel: 14,
    neighbors: []
  },
  {
    number: 114,
    district: 114,
    cadastralNumber: 41122,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10M',
    parcel: 13,
    neighbors: []
  },
  {
    number: 115,
    district: 114,
    cadastralNumber: 41121,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10M',
    parcel: 12,
    neighbors: []
  },
  {
    number: 116,
    district: 114,
    cadastralNumber: 41120,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10M',
    parcel: 11,
    neighbors: []
  },
  {
    number: 117,
    district: 114,
    cadastralNumber: 29850,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10M',
    parcel: 1,
    neighbors: []
  },
  {
    number: 118,
    district: 114,
    cadastralNumber: 41111,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10M',
    parcel: 2,
    neighbors: []
  },
  {
    number: 119,
    district: 114,
    cadastralNumber: 41112,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10M',
    parcel: 3,
    neighbors: []
  },
  {
    number: 120,
    district: 114,
    cadastralNumber: 41113,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10M',
    parcel: 4,
    neighbors: []
  },
  {
    number: 121,
    district: 114,
    cadastralNumber: 41114,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10M',
    parcel: 5,
    neighbors: []
  },
  {
    number: 122,
    district: 114,
    cadastralNumber: 41115,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10M',
    parcel: 6,
    neighbors: []
  },
  {
    number: 123,
    district: 114,
    cadastralNumber: 41116,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10M',
    parcel: 7,
    neighbors: []
  },
  {
    number: 124,
    district: 114,
    cadastralNumber: 41117,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10M',
    parcel: 8,
    neighbors: []
  },
  {
    number: 125,
    district: 114,
    cadastralNumber: 41118,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10M',
    parcel: 9,
    neighbors: []
  },
  {
    number: 126,
    district: 114,
    cadastralNumber: 41119,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10M',
    parcel: 10,
    neighbors: []
  },
  {
    number: 127,
    district: 114,
    cadastralNumber: 41072,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10F',
    parcel: 20,
    neighbors: []
  },
  {
    number: 128,
    district: 114,
    cadastralNumber: 41071,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10F',
    parcel: 19,
    neighbors: []
  },
  {
    number: 129,
    district: 114,
    cadastralNumber: 41070,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10F',
    parcel: 18,
    neighbors: []
  },
  {
    number: 130,
    district: 114,
    cadastralNumber: 41069,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10F',
    parcel: 17,
    neighbors: []
  },
  {
    number: 131,
    district: 114,
    cadastralNumber: 41068,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10F',
    parcel: 16,
    neighbors: []
  },
  {
    number: 132,
    district: 114,
    cadastralNumber: 41067,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10F',
    parcel: 15,
    neighbors: []
  },
  {
    number: 133,
    district: 114,
    cadastralNumber: 41066,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10F',
    parcel: 14,
    neighbors: []
  },
  {
    number: 134,
    district: 114,
    cadastralNumber: 41065,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10F',
    parcel: 13,
    neighbors: []
  },
  {
    number: 135,
    district: 114,
    cadastralNumber: 41064,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10F',
    parcel: 12,
    neighbors: []
  },
  {
    number: 136,
    district: 114,
    cadastralNumber: 41063,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10F',
    parcel: 11,
    neighbors: []
  },
  {
    number: 137,
    district: 114,
    cadastralNumber: 41059,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10F',
    parcel: 7,
    neighbors: []
  },
  {
    number: 138,
    district: 114,
    cadastralNumber: 41060,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10F',
    parcel: 8,
    neighbors: []
  },
  {
    number: 139,
    district: 114,
    cadastralNumber: 41061,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10F',
    parcel: 9,
    neighbors: []
  },
  {
    number: 140,
    district: 114,
    cadastralNumber: 41062,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10F',
    parcel: 10,
    neighbors: []
  },
  {
    number: 141,
    district: 114,
    cadastralNumber: 41247,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10Y',
    parcel: 1,
    neighbors: []
  },
  {
    number: 142,
    district: 114,
    cadastralNumber: 41248,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10Y',
    parcel: 2,
    neighbors: []
  },
  {
    number: 143,
    district: 114,
    cadastralNumber: 41249,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10Y',
    parcel: 3,
    neighbors: []
  },
  {
    number: 144,
    district: 114,
    cadastralNumber: 41250,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10Y',
    parcel: 4,
    neighbors: []
  },
  {
    number: 145,
    district: 114,
    cadastralNumber: 41251,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10Y',
    parcel: 5,
    neighbors: []
  },
  {
    number: 146,
    district: 114,
    cadastralNumber: 41252,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10Y',
    parcel: 6,
    neighbors: []
  },
  {
    number: 147,
    district: 114,
    cadastralNumber: 41253,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10Y',
    parcel: 7,
    neighbors: []
  },
  {
    number: 148,
    district: 114,
    cadastralNumber: 41254,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10Y',
    parcel: 8,
    neighbors: []
  },
  {
    number: 149,
    district: 114,
    cadastralNumber: 41255,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10Y',
    parcel: 9,
    neighbors: []
  },
  {
    number: 150,
    district: 114,
    cadastralNumber: 41256,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10Y',
    parcel: 10,
    neighbors: []
  },
  {
    number: 151,
    district: 114,
    cadastralNumber: 41257,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10Y',
    parcel: 11,
    neighbors: []
  },
  {
    number: 152,
    district: 114,
    cadastralNumber: 41258,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10Y',
    parcel: 12,
    neighbors: []
  },
  {
    number: 153,
    district: 114,
    cadastralNumber: 41210,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10T',
    parcel: 24,
    neighbors: []
  },
  {
    number: 154,
    district: 114,
    cadastralNumber: 41209,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10T',
    parcel: 23,
    neighbors: []
  },
  {
    number: 155,
    district: 114,
    cadastralNumber: 41208,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10T',
    parcel: 22,
    neighbors: []
  },
  {
    number: 156,
    district: 114,
    cadastralNumber: 41207,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10T',
    parcel: 21,
    neighbors: []
  },
  {
    number: 157,
    district: 114,
    cadastralNumber: 41206,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10T',
    parcel: 20,
    neighbors: []
  },
  {
    number: 158,
    district: 114,
    cadastralNumber: 41205,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10T',
    parcel: 19,
    neighbors: []
  },
  {
    number: 159,
    district: 114,
    cadastralNumber: 41204,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10T',
    parcel: 18,
    neighbors: []
  },
  {
    number: 160,
    district: 114,
    cadastralNumber: 41203,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10T',
    parcel: 17,
    neighbors: []
  },
  {
    number: 161,
    district: 114,
    cadastralNumber: 41202,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10T',
    parcel: 16,
    neighbors: []
  },
  {
    number: 162,
    district: 114,
    cadastralNumber: 41201,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10T',
    parcel: 15,
    neighbors: []
  },
  {
    number: 163,
    district: 114,
    cadastralNumber: 41200,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10T',
    parcel: 14,
    neighbors: []
  },
  {
    number: 164,
    district: 114,
    cadastralNumber: 41199,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10T',
    parcel: 13,
    neighbors: []
  },
  {
    number: 165,
    district: 114,
    cadastralNumber: 29851,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10T',
    parcel: 1,
    neighbors: []
  },
  {
    number: 166,
    district: 114,
    cadastralNumber: 41188,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10T',
    parcel: 2,
    neighbors: []
  },
  {
    number: 167,
    district: 114,
    cadastralNumber: 41189,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10T',
    parcel: 3,
    neighbors: []
  },
  {
    number: 168,
    district: 114,
    cadastralNumber: 41190,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10T',
    parcel: 4,
    neighbors: []
  },
  {
    number: 169,
    district: 114,
    cadastralNumber: 41191,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10T',
    parcel: 5,
    neighbors: []
  },
  {
    number: 170,
    district: 114,
    cadastralNumber: 41192,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10T',
    parcel: 6,
    neighbors: []
  },
  {
    number: 171,
    district: 114,
    cadastralNumber: 41193,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10T',
    parcel: 7,
    neighbors: []
  },
  {
    number: 172,
    district: 114,
    cadastralNumber: 41194,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10T',
    parcel: 8,
    neighbors: []
  },
  {
    number: 173,
    district: 114,
    cadastralNumber: 41195,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10T',
    parcel: 9,
    neighbors: []
  },
  {
    number: 174,
    district: 114,
    cadastralNumber: 41196,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10T',
    parcel: 10,
    neighbors: []
  },
  {
    number: 175,
    district: 114,
    cadastralNumber: 41197,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10T',
    parcel: 11,
    neighbors: []
  },
  {
    number: 176,
    district: 114,
    cadastralNumber: 41198,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10T',
    parcel: 12,
    neighbors: []
  },
  {
    number: 177,
    district: 114,
    cadastralNumber: 41153,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10N',
    parcel: 24,
    neighbors: []
  },
  {
    number: 178,
    district: 114,
    cadastralNumber: 41152,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10N',
    parcel: 23,
    neighbors: []
  },
  {
    number: 179,
    district: 114,
    cadastralNumber: 41151,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10N',
    parcel: 22,
    neighbors: []
  },
  {
    number: 180,
    district: 114,
    cadastralNumber: 41150,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10N',
    parcel: 21,
    neighbors: []
  },
  {
    number: 181,
    district: 114,
    cadastralNumber: 41149,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10N',
    parcel: 20,
    neighbors: []
  },
  {
    number: 182,
    district: 114,
    cadastralNumber: 41148,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10N',
    parcel: 19,
    neighbors: []
  },
  {
    number: 183,
    district: 114,
    cadastralNumber: 41147,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10N',
    parcel: 18,
    neighbors: []
  },
  {
    number: 184,
    district: 114,
    cadastralNumber: 41146,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10N',
    parcel: 17,
    neighbors: []
  },
  {
    number: 185,
    district: 114,
    cadastralNumber: 41145,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10N',
    parcel: 16,
    neighbors: []
  },
  {
    number: 186,
    district: 114,
    cadastralNumber: 41144,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10N',
    parcel: 15,
    neighbors: []
  },
  {
    number: 187,
    district: 114,
    cadastralNumber: 41143,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10N',
    parcel: 14,
    neighbors: []
  },
  {
    number: 188,
    district: 114,
    cadastralNumber: 41142,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10N',
    parcel: 13,
    neighbors: []
  },
  {
    number: 189,
    district: 114,
    cadastralNumber: 41130,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10N',
    parcel: 1,
    neighbors: []
  },
  {
    number: 190,
    district: 114,
    cadastralNumber: 41131,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10N',
    parcel: 2,
    neighbors: []
  },
  {
    number: 191,
    district: 114,
    cadastralNumber: 41132,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10N',
    parcel: 3,
    neighbors: []
  },
  {
    number: 192,
    district: 114,
    cadastralNumber: 41133,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10N',
    parcel: 4,
    neighbors: []
  },
  {
    number: 193,
    district: 114,
    cadastralNumber: 41134,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10N',
    parcel: 5,
    neighbors: []
  },
  {
    number: 194,
    district: 114,
    cadastralNumber: 41135,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10N',
    parcel: 6,
    neighbors: []
  },
  {
    number: 195,
    district: 114,
    cadastralNumber: 41136,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10N',
    parcel: 7,
    neighbors: []
  },
  {
    number: 196,
    district: 114,
    cadastralNumber: 41137,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10N',
    parcel: 8,
    neighbors: []
  },
  {
    number: 197,
    district: 114,
    cadastralNumber: 41138,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10N',
    parcel: 9,
    neighbors: []
  },
  {
    number: 198,
    district: 114,
    cadastralNumber: 41139,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10N',
    parcel: 10,
    neighbors: []
  },
  {
    number: 199,
    district: 114,
    cadastralNumber: 41140,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10N',
    parcel: 11,
    neighbors: []
  },
  {
    number: 200,
    district: 114,
    cadastralNumber: 41141,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10N',
    parcel: 12,
    neighbors: []
  },
  {
    number: 201,
    district: 114,
    cadastralNumber: 41095,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10G',
    parcel: 24,
    neighbors: []
  },
  {
    number: 202,
    district: 114,
    cadastralNumber: 41094,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10G',
    parcel: 23,
    neighbors: []
  },
  {
    number: 203,
    district: 114,
    cadastralNumber: 41093,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10G',
    parcel: 22,
    neighbors: []
  },
  {
    number: 204,
    district: 114,
    cadastralNumber: 41092,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10G',
    parcel: 21,
    neighbors: []
  },
  {
    number: 205,
    district: 114,
    cadastralNumber: 41091,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10G',
    parcel: 20,
    neighbors: []
  },
  {
    number: 206,
    district: 114,
    cadastralNumber: 41090,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10G',
    parcel: 19,
    neighbors: []
  },
  {
    number: 207,
    district: 114,
    cadastralNumber: 41089,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10G',
    parcel: 18,
    neighbors: []
  },
  {
    number: 208,
    district: 114,
    cadastralNumber: 41088,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10G',
    parcel: 17,
    neighbors: []
  },
  {
    number: 209,
    district: 114,
    cadastralNumber: 41087,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10G',
    parcel: 16,
    neighbors: []
  },
  {
    number: 210,
    district: 114,
    cadastralNumber: 41086,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10G',
    parcel: 15,
    neighbors: []
  },
  {
    number: 211,
    district: 114,
    cadastralNumber: 41085,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10G',
    parcel: 14,
    neighbors: []
  },
  {
    number: 212,
    district: 114,
    cadastralNumber: 41084,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10G',
    parcel: 13,
    neighbors: []
  },
  {
    number: 213,
    district: 114,
    cadastralNumber: 29843,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10G',
    parcel: 1,
    neighbors: []
  },
  {
    number: 214,
    district: 114,
    cadastralNumber: 41073,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10G',
    parcel: 2,
    neighbors: []
  },
  {
    number: 215,
    district: 114,
    cadastralNumber: 41074,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10G',
    parcel: 3,
    neighbors: []
  },
  {
    number: 216,
    district: 114,
    cadastralNumber: 41075,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10G',
    parcel: 4,
    neighbors: []
  },
  {
    number: 217,
    district: 114,
    cadastralNumber: 41076,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10G',
    parcel: 5,
    neighbors: []
  },
  {
    number: 218,
    district: 114,
    cadastralNumber: 41077,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10G',
    parcel: 6,
    neighbors: []
  },
  {
    number: 219,
    district: 114,
    cadastralNumber: 41078,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10G',
    parcel: 7,
    neighbors: []
  },
  {
    number: 220,
    district: 114,
    cadastralNumber: 41079,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10G',
    parcel: 8,
    neighbors: []
  },
  {
    number: 221,
    district: 114,
    cadastralNumber: 41080,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10G',
    parcel: 9,
    neighbors: []
  },
  {
    number: 222,
    district: 114,
    cadastralNumber: 41081,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10G',
    parcel: 10,
    neighbors: []
  },
  {
    number: 223,
    district: 114,
    cadastralNumber: 41082,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10G',
    parcel: 11,
    neighbors: []
  },
  {
    number: 224,
    district: 114,
    cadastralNumber: 41083,
    cadastralJurisdiction: 7,
    section: 'O',
    subdivision: 10,
    block: '10G',
    parcel: 12,
    neighbors: []
  }
];
